### PR TITLE
Add friendly reminder to future travelers

### PR DESCRIPTION
**Pull request by pirog**
@bcauldwell just added a little reminder here. please merge when you can.

### CODE REVIEW

**Comment by pirog** [comment]
@bcauldwell bump on the PR here.

**Comment by hhcauldwell** [comment]
@bcauldwell test

**Comment by hhcauldwell** [comment]
@bcauldwell testing

**Comment by pirog** [comment]
@bcauldwell @bcauldwell @bcauldwell @bcauldwell @bcauldwell @bcauldwell @bcauldwell @bcauldwell @bcauldwell @bcauldwell @bcauldwell @bcauldwell @bcauldwell @bcauldwell @bcauldwell @bcauldwell @bcauldwell @bcauldwell @bcauldwell @bcauldwell @bcauldwell @bcauldwell @bcauldwell @bcauldwell @bcauldwell @bcauldwell @bcauldwell @bcauldwell @bcauldwell @bcauldwell @bcauldwell @bcauldwell @bcauldwell @bcauldwell @bcauldwell @bcauldwell @bcauldwell @bcauldwell @bcauldwell @bcauldwell @bcauldwell @bcauldwell @bcauldwell @bcauldwell @bcauldwell @bcauldwell @bcauldwell @bcauldwell @bcauldwell @bcauldwell

**Pull request merged**
